Documentation:
  Enabled: false


Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/*

Lint/AmbiguousBlockAssociation:
  Enabled: false

Metrics/LineLength:
  Max: 105

AllCops:
  Exclude:
    - '**/Rakefile'
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'spec/*_helper.rb'
    - 'tmp/**/*'
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'test/**/*'
